export type CardData = {
  id: string
  title: string
  subtitle: string
  description: string
  tag: string
  keywords: string[]
  themes: string[]
  symbol: string
  image?: string
  actionTitle: string
  actions: string[]
}

export const CARDS: CardData[] = [
  {
    id: "bluff",
    title: "The Bluff",
    subtitle: "False signal of value",
    description: "You're focusing on something that feels important, but isn't.",
    tag: "perceived importance",
    keywords: ["focus", "priority", "roadmap", "strategy", "align", "important", "initiative", "visible", "perception"],
    themes: ["strategy", "focus"],
    symbol: "♠",
    image: "/cards/bluff.png",
    actionTitle: "Refocus on real impact",
    actions: [
      "List your current priorities",
      "Tie each one to a real outcome (revenue, retention, activation)",
      "Drop anything that doesn't clearly move a metric",
      "Focus your next sprint on one measurable result",
    ],
  },
  {
    id: "signal",
    title: "The Signal",
    subtitle: "Data speaks in whispers",
    description: "There's a pattern in your data you're choosing to ignore.",
    tag: "ignored data",
    keywords: ["data", "metrics", "analytics", "signal", "insight", "pattern", "trend"],
    themes: ["metrics", "user_research"],
    symbol: "◈",
    actionTitle: "Stop ignoring what the data is telling you",
    actions: [
      "Pull your top 3 drop-off points this week",
      "Find the trend you've been explaining away",
      "Run one experiment based on that signal",
      "Set a weekly review to track if it moves",
    ],
  },
  {
    id: "fold",
    title: "The Fold",
    subtitle: "A necessary ending",
    description: "You know this isn't working. You just haven't admitted it yet.",
    tag: "sunk cost",
    keywords: ["feature", "kill", "cut", "remove", "simplify", "scope", "bloat", "complex", "admit", "end"],
    themes: ["focus", "strategy"],
    symbol: "✕",
    image: "/cards/the-fold.png",
    actionTitle: "Kill it cleanly",
    actions: [
      "Write down why this isn't working",
      "Decide what success would look like (be honest)",
      "If you're not close, stop investing more time",
      "Communicate clearly and move on",
    ],
  },
  {
    id: "lack-of-focus",
    title: "Lack of Focus",
    subtitle: "The scattered path",
    description: "You're trying to do too many things, so none of them work.",
    tag: "too many paths",
    keywords: ["spread", "thin", "multiple", "projects", "team", "resources", "focus", "scattered", "direction", "priorities"],
    themes: ["focus", "growth"],
    symbol: "◆",
    image: "/cards/lack-of-focus.png",
    actionTitle: "Reduce scope aggressively",
    actions: [
      "List all active initiatives",
      "Kill or pause at least 50% of them",
      "Focus the team on one clear goal",
      "Say no to anything new for the next sprint",
    ],
  },
  {
    id: "hidden-cost",
    title: "Hidden Cost",
    subtitle: "What the ledger conceals",
    description: "The thing you're not measuring is the thing that's killing you.",
    tag: "blind spot",
    keywords: ["cost", "hidden", "measure", "blind", "overhead", "debt", "maintenance", "invisible"],
    themes: ["metrics", "pricing"],
    symbol: "⊘",
    actionTitle: "Find and measure your blind spot",
    actions: [
      "List every assumption behind your current strategy",
      "Identify which ones you've never validated with data",
      "Add one new metric this week that tracks the blind spot",
      "Review it in your next team sync",
    ],
  },
  {
    id: "false-momentum",
    title: "False Momentum",
    subtitle: "Movement without direction",
    description: "You're shipping things, but nothing is actually getting better.",
    tag: "motion without progress",
    keywords: ["ship", "velocity", "speed", "fast", "output", "busy", "release", "sprint", "progress", "momentum"],
    themes: ["growth", "strategy"],
    symbol: "↻",
    image: "/cards/false-momentum.png",
    actionTitle: "Replace activity with progress",
    actions: [
      "Define one metric that actually matters this week",
      "Check if your current work impacts it directly",
      "Cut tasks that don't move that metric",
      "Ship one change that should visibly move it",
    ],
  },
  {
    id: "premature",
    title: "Premature Optimization",
    subtitle: "The illusion of progress",
    description: "You're polishing a product that hasn't earned it yet.",
    tag: "premature polish",
    keywords: ["optimize", "polish", "perfect", "scale", "premature", "early", "launch", "mvp"],
    themes: ["onboarding", "growth"],
    symbol: "◎",
    image: "/cards/premature.png",
    actionTitle: "Stop polishing, start validating",
    actions: [
      "Identify the core user action that defines value",
      "Check if new users reach it within the first session",
      "If not, simplify instead of improving visuals",
      "Ship something faster instead of making it perfect",
    ],
  },
  {
    id: "wrong-metric-focus",
    title: "Wrong Metric Focus",
    subtitle: "The false scoreboard",
    description: "You're tracking what looks good, not what matters.",
    tag: "distorted quest",
    keywords: ["metric", "vanity", "growth", "number", "dashboard", "report", "kpi", "wrong", "track", "measure"],
    themes: ["metrics", "growth"],
    symbol: "◐",
    image: "/cards/wrong-metric-focus.png",
    actionTitle: "Fix the scoreboard",
    actions: [
      "Identify your main success metric",
      "Ask: does it reflect real user value?",
      "If not, redefine it (e.g. activation, retention)",
      "Align team work to improving that metric only",
    ],
  },
  {
    id: "stall",
    title: "The Stall",
    subtitle: "The paralysis of maybe",
    description: "You've stopped making hard decisions and it shows.",
    tag: "indecision",
    keywords: ["stuck", "stall", "decision", "slow", "committee", "consensus", "blocked", "wait"],
    themes: ["strategy", "focus"],
    symbol: "⏸",
    actionTitle: "Make the decision you've been avoiding",
    actions: [
      "Write down the decision you've been postponing",
      "Set a 48-hour deadline to make it",
      "Accept that 80% confidence is enough to move",
      "Communicate it and don't revisit for two weeks",
    ],
  },
  {
    id: "shortcut",
    title: "The Shortcut",
    subtitle: "The longest road home",
    description: "The shortcut you took is now your longest path.",
    tag: "tech debt",
    keywords: ["shortcut", "hack", "debt", "quick", "workaround", "technical", "patch", "fix"],
    themes: ["focus", "strategy"],
    symbol: "⚡",
    actionTitle: "Pay down the debt before it compounds",
    actions: [
      "List every workaround your team knows about",
      "Rank them by how much they slow you down weekly",
      "Dedicate 20% of next sprint to fixing the top one",
      "Document the fix so it doesn't come back",
    ],
  },
  {
    id: "echo",
    title: "The Echo Chamber",
    subtitle: "A distortion of signal",
    description: "You're not listening to users. You're filtering them.",
    tag: "confirmation bias",
    keywords: ["user", "research", "feedback", "survey", "interview", "listen", "customer", "opinion", "bias", "filter"],
    themes: ["user_research", "metrics"],
    symbol: "◉",
    image: "/cards/echo-chamber.png",
    actionTitle: "Get real signal",
    actions: [
      "Talk to users who churned or didn't convert",
      "Ask open-ended questions, not leading ones",
      "Look for patterns, not validation",
      "Write down what contradicts your beliefs",
    ],
  },
  {
    id: "drift",
    title: "The Drift",
    subtitle: "Lost compass, open sea",
    description: "You've lost sight of the original problem you set out to solve.",
    tag: "mission drift",
    keywords: ["mission", "vision", "original", "problem", "pivot", "direction", "purpose", "why"],
    themes: ["strategy", "growth"],
    symbol: "∿",
    actionTitle: "Get back to the real problem",
    actions: [
      "Write down the original problem you set out to solve",
      "Ask: does what we're building today actually solve this?",
      "Talk to 3 real users and confirm the problem still exists",
      "Cut anything not directly tied to that problem",
    ],
  },
  {
    id: "feature-overload",
    title: "Feature Overload",
    subtitle: "The scattered offering",
    description: "You're adding more, because nothing you built is working.",
    tag: "too much, too fast",
    keywords: ["feature", "add", "more", "scope", "creep", "build", "launch", "bloat", "overload", "pile"],
    themes: ["focus", "growth"],
    symbol: "⊕",
    image: "/cards/feature-overload.png",
    actionTitle: "Simplify to find signal",
    actions: [
      "List your last 5 shipped features",
      "Check which ones are actually used",
      "Remove or hide low-usage features",
      "Double down on the one that delivers value",
    ],
  },
  {
    id: "false-stability",
    title: "False Stability",
    subtitle: "An illusion of strength",
    description: "Things look stable, but the core is weaker than you think.",
    tag: "fragile foundation",
    keywords: ["stable", "foundation", "infrastructure", "fragile", "break", "risk", "system", "reliable", "resilience", "collapse"],
    themes: ["strategy", "metrics"],
    symbol: "⚖",
    image: "/cards/false-stability.png",
    actionTitle: "Stress-test your foundation",
    actions: [
      "Identify your biggest assumption (e.g. users actually care)",
      "Run a quick test to validate or break it",
      "Look at real user behavior, not dashboards",
      "Prepare a fallback if that assumption fails",
    ],
  },
]
