export type CardData = {
  id: string
  title: string
  subtitle: string
  description: string
  tag: string
  keywords: string[]
  phrases: string[]
  synonyms: string[]
  themes: string[]
  symbol: string
  image?: string
  actionTitle: string
  actions: string[]
}

export const CARDS: CardData[] = [
  {
    id: "bluff",
    title: "The Bluff",
    subtitle: "False signal of value",
    description: "You're focusing on something that feels important, but isn't.",
    tag: "perceived importance",
    keywords: ["focus", "priority", "roadmap", "strategy", "align", "important", "initiative", "visible", "perception", "stakeholder", "optics", "appearance"],
    phrases: [
      "feels important but", "looks good on paper", "stakeholder request", "executive priority",
      "not moving the needle", "vanity project", "political initiative", "sounds strategic",
      "hard to say no", "everyone wants this", "leadership wants", "board presentation",
    ],
    synonyms: ["impression", "status", "reporting", "agenda", "showcase", "demo", "pitch", "slide", "deck"],
    themes: ["strategy", "focus"],
    symbol: "♠",
    image: "/cards/bluff.png",
    actionTitle: "Refocus on real impact",
    actions: [
      "List your current priorities",
      "Tie each one to a real outcome (revenue, retention, activation)",
      "Drop anything that doesn't clearly move a metric",
      "Focus your next sprint on one measurable result",
    ],
  },
  {
    id: "signal",
    title: "The Signal",
    subtitle: "Data speaks in whispers",
    description: "There's a pattern in your data you're choosing to ignore.",
    tag: "ignored data",
    keywords: ["data", "metrics", "analytics", "signal", "insight", "pattern", "trend", "dashboard", "numbers", "report", "anomaly", "correlation"],
    phrases: [
      "data shows", "the numbers say", "ignoring the data", "not looking at",
      "drop off", "conversion rate", "funnel analysis", "cohort analysis",
      "we don't track", "no visibility into", "haven't measured", "don't know why",
    ],
    synonyms: ["chart", "graph", "tracking", "telemetry", "monitoring", "log", "event", "segment"],
    themes: ["metrics", "user_research"],
    symbol: "◈",
    actionTitle: "Stop ignoring what the data is telling you",
    actions: [
      "Pull your top 3 drop-off points this week",
      "Find the trend you've been explaining away",
      "Run one experiment based on that signal",
      "Set a weekly review to track if it moves",
    ],
  },
  {
    id: "fold",
    title: "The Fold",
    subtitle: "A necessary ending",
    description: "You know this isn't working. You just haven't admitted it yet.",
    tag: "sunk cost",
    keywords: ["feature", "kill", "cut", "remove", "simplify", "scope", "bloat", "complex", "admit", "end", "sunset", "deprecate", "abandon"],
    phrases: [
      "not working but", "invested too much", "sunk cost", "can't let go",
      "already spent", "too far in", "kill the feature", "shut it down",
      "nobody uses it", "low adoption", "failed experiment", "should we stop",
    ],
    synonyms: ["waste", "legacy", "old", "outdated", "unused", "dead", "zombie", "archive"],
    themes: ["focus", "strategy", "decision_making"],
    symbol: "✕",
    image: "/cards/the-fold.png",
    actionTitle: "Kill it cleanly",
    actions: [
      "Write down why this isn't working",
      "Decide what success would look like (be honest)",
      "If you're not close, stop investing more time",
      "Communicate clearly and move on",
    ],
  },
  {
    id: "lack-of-focus",
    title: "Lack of Focus",
    subtitle: "The scattered path",
    description: "You're trying to do too many things, so none of them work.",
    tag: "too many paths",
    keywords: ["spread", "thin", "multiple", "projects", "team", "resources", "focus", "scattered", "direction", "priorities", "parallel", "initiatives", "bandwidth"],
    phrases: [
      "too many things", "spread too thin", "doing everything", "no clear priority",
      "working on multiple", "can't say no", "everything is priority one", "juggling too many",
      "team is stretched", "no bandwidth", "context switching", "too many projects",
    ],
    synonyms: ["overwhelmed", "distracted", "fragmented", "diluted", "overloaded", "multitask", "busy", "chaotic"],
    themes: ["focus", "growth", "leadership"],
    symbol: "◆",
    image: "/cards/lack-of-focus.png",
    actionTitle: "Reduce scope aggressively",
    actions: [
      "List all active initiatives",
      "Kill or pause at least 50% of them",
      "Focus the team on one clear goal",
      "Say no to anything new for the next sprint",
    ],
  },
  {
    id: "hidden-cost",
    title: "Hidden Cost",
    subtitle: "What the ledger conceals",
    description: "The thing you're not measuring is the thing that's killing you.",
    tag: "blind spot",
    keywords: ["cost", "hidden", "measure", "blind", "overhead", "debt", "maintenance", "invisible", "support", "burden", "complexity", "expense"],
    phrases: [
      "hidden cost of", "not measuring", "blind spot", "didn't account for",
      "true cost", "total cost of ownership", "support burden", "maintenance overhead",
      "technical debt", "operational cost", "nobody tracks", "invisible tax",
    ],
    synonyms: ["overhead", "waste", "drag", "friction", "inefficiency", "leakage", "drain", "tax"],
    themes: ["metrics", "pricing", "tech_debt"],
    symbol: "⊘",
    actionTitle: "Find and measure your blind spot",
    actions: [
      "List every assumption behind your current strategy",
      "Identify which ones you've never validated with data",
      "Add one new metric this week that tracks the blind spot",
      "Review it in your next team sync",
    ],
  },
  {
    id: "false-momentum",
    title: "False Momentum",
    subtitle: "Movement without direction",
    description: "You're shipping things, but nothing is actually getting better.",
    tag: "motion without progress",
    keywords: ["ship", "velocity", "speed", "fast", "output", "busy", "release", "sprint", "progress", "momentum", "deploy", "launch", "cadence"],
    phrases: [
      "shipping but nothing changes", "busy but not moving", "lots of output no outcomes",
      "release cadence", "sprint velocity", "shipping fast but", "deploying often but",
      "motion without progress", "activity not progress", "doing a lot but", "high velocity low impact",
    ],
    synonyms: ["hustle", "grind", "throughput", "productive", "active", "working", "executing", "delivering"],
    themes: ["growth", "strategy", "metrics"],
    symbol: "↻",
    image: "/cards/false-momentum.png",
    actionTitle: "Replace activity with progress",
    actions: [
      "Define one metric that actually matters this week",
      "Check if your current work impacts it directly",
      "Cut tasks that don't move that metric",
      "Ship one change that should visibly move it",
    ],
  },
  {
    id: "premature",
    title: "Premature Optimization",
    subtitle: "The illusion of progress",
    description: "You're polishing a product that hasn't earned it yet.",
    tag: "premature polish",
    keywords: ["optimize", "polish", "perfect", "scale", "premature", "early", "launch", "mvp", "iterate", "validate", "prototype", "refine"],
    phrases: [
      "product market fit", "too early to scale", "polishing before launching",
      "not ready to optimize", "premature scaling", "perfecting the design",
      "before we have users", "building for scale", "over-engineering", "gold plating",
      "haven't validated yet", "no users yet but",
    ],
    synonyms: ["design", "ui", "visual", "tweak", "improvement", "quality", "pixel", "craft", "details", "beautiful"],
    themes: ["onboarding", "growth", "product_market_fit"],
    symbol: "◎",
    image: "/cards/premature.png",
    actionTitle: "Stop polishing, start validating",
    actions: [
      "Identify the core user action that defines value",
      "Check if new users reach it within the first session",
      "If not, simplify instead of improving visuals",
      "Ship something faster instead of making it perfect",
    ],
  },
  {
    id: "wrong-metric-focus",
    title: "Wrong Metric Focus",
    subtitle: "The false scoreboard",
    description: "You're tracking what looks good, not what matters.",
    tag: "distorted quest",
    keywords: ["metric", "vanity", "growth", "number", "dashboard", "report", "kpi", "wrong", "track", "measure", "pageviews", "downloads", "signups"],
    phrases: [
      "vanity metrics", "wrong metric", "looks good on paper", "tracking the wrong thing",
      "optimizing the wrong", "north star metric", "pageviews not revenue", "downloads not retention",
      "signups not activation", "measuring what's easy", "reporting to the board", "hockey stick graph",
    ],
    synonyms: ["impressions", "likes", "followers", "views", "visits", "registrations", "count", "volume"],
    themes: ["metrics", "growth", "experimentation"],
    symbol: "◐",
    image: "/cards/wrong-metric-focus.png",
    actionTitle: "Fix the scoreboard",
    actions: [
      "Identify your main success metric",
      "Ask: does it reflect real user value?",
      "If not, redefine it (e.g. activation, retention)",
      "Align team work to improving that metric only",
    ],
  },
  {
    id: "stall",
    title: "The Stall",
    subtitle: "The paralysis of maybe",
    description: "You've stopped making hard decisions and it shows.",
    tag: "indecision",
    keywords: ["stuck", "stall", "decision", "slow", "committee", "consensus", "blocked", "wait", "postpone", "delay", "indecisive", "paralysis"],
    phrases: [
      "can't decide", "waiting for alignment", "need more data before", "not sure which direction",
      "analysis paralysis", "too many stakeholders", "decision by committee", "keep pushing back",
      "blocked on approval", "waiting for leadership", "no clear owner", "nobody wants to call it",
    ],
    synonyms: ["hesitate", "defer", "stagnate", "unclear", "ambiguous", "uncertain", "pending", "limbo"],
    themes: ["strategy", "focus", "decision_making", "leadership"],
    symbol: "⏸",
    actionTitle: "Make the decision you've been avoiding",
    actions: [
      "Write down the decision you've been postponing",
      "Set a 48-hour deadline to make it",
      "Accept that 80% confidence is enough to move",
      "Communicate it and don't revisit for two weeks",
    ],
  },
  {
    id: "shortcut",
    title: "The Shortcut",
    subtitle: "The longest road home",
    description: "The shortcut you took is now your longest path.",
    tag: "tech debt",
    keywords: ["shortcut", "hack", "debt", "quick", "workaround", "technical", "patch", "fix", "infrastructure", "migration", "refactor", "legacy"],
    phrases: [
      "technical debt", "quick fix that stuck", "workaround became permanent",
      "duct tape solution", "tech debt piling up", "legacy system", "migration needed",
      "should have done it right", "keeping the lights on", "band-aid solution",
      "infrastructure holding us back", "can't ship because of",
    ],
    synonyms: ["code", "engineering", "architecture", "backend", "system", "codebase", "monolith", "spaghetti"],
    themes: ["focus", "strategy", "tech_debt"],
    symbol: "⚡",
    actionTitle: "Pay down the debt before it compounds",
    actions: [
      "List every workaround your team knows about",
      "Rank them by how much they slow you down weekly",
      "Dedicate 20% of next sprint to fixing the top one",
      "Document the fix so it doesn't come back",
    ],
  },
  {
    id: "echo",
    title: "The Echo Chamber",
    subtitle: "A distortion of signal",
    description: "You're not listening to users. You're filtering them.",
    tag: "confirmation bias",
    keywords: ["user", "research", "feedback", "survey", "interview", "listen", "customer", "opinion", "bias", "filter", "validate", "confirm"],
    phrases: [
      "users say they want", "we already know what users want", "our users love it",
      "confirmation bias", "cherry picking feedback", "only talking to power users",
      "not listening to churned users", "internal opinion vs user data",
      "we think users want", "nobody asked the users", "assumed users would",
    ],
    synonyms: ["perception", "assumption", "intuition", "gut", "belief", "hypothesis", "conviction", "narrative"],
    themes: ["user_research", "metrics", "experimentation"],
    symbol: "◉",
    image: "/cards/echo-chamber.png",
    actionTitle: "Get real signal",
    actions: [
      "Talk to users who churned or didn't convert",
      "Ask open-ended questions, not leading ones",
      "Look for patterns, not validation",
      "Write down what contradicts your beliefs",
    ],
  },
  {
    id: "drift",
    title: "The Drift",
    subtitle: "Lost compass, open sea",
    description: "You've lost sight of the original problem you set out to solve.",
    tag: "mission drift",
    keywords: ["mission", "vision", "original", "problem", "pivot", "direction", "purpose", "why", "scope", "evolve", "changed", "lost"],
    phrases: [
      "lost sight of", "original problem", "mission creep", "scope expanded",
      "what are we even building", "why did we start this", "pivoted too many times",
      "the product has drifted", "no longer solving the original", "feature factory",
      "lost the plot", "forgot why we started",
    ],
    synonyms: ["identity", "core", "foundation", "essence", "principle", "value", "origin", "root"],
    themes: ["strategy", "growth", "product_market_fit"],
    symbol: "∿",
    actionTitle: "Get back to the real problem",
    actions: [
      "Write down the original problem you set out to solve",
      "Ask: does what we're building today actually solve this?",
      "Talk to 3 real users and confirm the problem still exists",
      "Cut anything not directly tied to that problem",
    ],
  },
  {
    id: "feature-overload",
    title: "Feature Overload",
    subtitle: "The scattered offering",
    description: "You're adding more, because nothing you built is working.",
    tag: "too much, too fast",
    keywords: ["feature", "add", "more", "scope", "creep", "build", "launch", "bloat", "overload", "pile", "complex", "settings", "options"],
    phrases: [
      "too many features", "feature creep", "scope creep", "adding more features",
      "users are confused", "product is bloated", "nobody uses half the features",
      "we keep building but", "launched 10 features this quarter", "feature factory",
      "requests keep coming in", "roadmap is packed",
    ],
    synonyms: ["clutter", "noise", "overwhelming", "complicated", "confusing", "sprawl", "surface", "breadth"],
    themes: ["focus", "growth", "activation"],
    symbol: "⊕",
    image: "/cards/feature-overload.png",
    actionTitle: "Simplify to find signal",
    actions: [
      "List your last 5 shipped features",
      "Check which ones are actually used",
      "Remove or hide low-usage features",
      "Double down on the one that delivers value",
    ],
  },
  {
    id: "false-stability",
    title: "False Stability",
    subtitle: "An illusion of strength",
    description: "Things look stable, but the core is weaker than you think.",
    tag: "fragile foundation",
    keywords: ["stable", "foundation", "infrastructure", "fragile", "break", "risk", "system", "reliable", "resilience", "collapse", "dependency", "single"],
    phrases: [
      "looks stable but", "single point of failure", "fragile system", "one thing breaks and",
      "house of cards", "not built to last", "everything depends on", "key person risk",
      "no redundancy", "never been stress tested", "working by accident", "held together by",
    ],
    synonyms: ["brittle", "weak", "vulnerable", "exposed", "shaky", "precarious", "risky", "thin"],
    themes: ["strategy", "metrics", "tech_debt"],
    symbol: "⚖",
    image: "/cards/false-stability.png",
    actionTitle: "Stress-test your foundation",
    actions: [
      "Identify your biggest assumption (e.g. users actually care)",
      "Run a quick test to validate or break it",
      "Look at real user behavior, not dashboards",
      "Prepare a fallback if that assumption fails",
    ],
  },
]
